
server:
  servlet:
    contextPath: /talentConnect/api
spring:
  application:
    name: talentConnect
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/TalentConnect
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect